In [ ]:
import pandas as pd

# Load datasets
patients = pd.read_csv("/content/patients.csv")
doctors = pd.read_csv("/content/doctors.csv")
appointments = pd.read_csv("/content/appointments.csv")
billing = pd.read_csv("/content/billing.csv")
treatments = pd.read_csv("/content/treatments.csv")

In [ ]:
patients.head()

,patient_id,first_name,last_name,gender,date_of_birth,contact_number,address,registration_date,insurance_provider,insurance_number,email
0,P001,David,Williams,F,1955-06-04,6939585183,789 Pine Rd,2022-06-23,WellnessCorp,INS840674,david.williams@mail.com
1,P002,Emily,Smith,F,1984-10-12,8228188767,321 Maple Dr,2022-01-15,PulseSecure,INS354079,emily.smith@mail.com
2,P003,Laura,Jones,M,1977-08-21,8397029847,321 Maple Dr,2022-02-07,PulseSecure,INS650929,laura.jones@mail.com
3,P004,Michael,Johnson,F,1981-02-20,9019443432,123 Elm St,2021-03-02,HealthIndia,INS789944,michael.johnson@mail.com
4,P005,David,Wilson,M,1960-06-23,7734463155,123 Elm St,2021-09-29,MedCare Plus,INS788105,david.wilson@mail.com

In [ ]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          50 non-null     object
 1   first_name          50 non-null     object
 2   last_name           50 non-null     object
 3   gender              50 non-null     object
 4   date_of_birth       50 non-null     object
 5   contact_number      50 non-null     int64
 6   address             50 non-null     object
 7   registration_date   50 non-null     object
 8   insurance_provider  50 non-null     object
 9   insurance_number    50 non-null     object
 10  email               50 non-null     object
dtypes: int64(1), object(10)
memory usage: 4.4+ KB

In [ ]:
patients['date_of_birth'] = pd.to_datetime(patients['date_of_birth'])
patients['registration_date'] = pd.to_datetime(patients['registration_date'])

In [ ]:
patients.isnull().sum()

patient_id            0
first_name            0
last_name             0
gender                0
date_of_birth         0
contact_number        0
address               0
registration_date     0
insurance_provider    0
insurance_number      0
email                 0
dtype: int64

In [ ]:
patients.duplicated().sum()

np.int64(0)

In [ ]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show

In [ ]:
appointments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   appointment_id    200 non-null    object
 1   patient_id        200 non-null    object
 2   doctor_id         200 non-null    object
 3   appointment_date  200 non-null    object
 4   appointment_time  200 non-null    object
 5   reason_for_visit  200 non-null    object
 6   status            200 non-null    object
dtypes: object(7)
memory usage: 11.1+ KB

In [ ]:
appointments['AppointmentDateTime'] = pd.to_datetime(
    appointments['appointment_date'] + ' ' + appointments['appointment_time']
)

In [ ]:
appointments.isnull().sum()

appointment_id         0
patient_id             0
doctor_id              0
appointment_date       0
appointment_time       0
reason_for_visit       0
status                 0
AppointmentDateTime    0
dtype: int64

In [ ]:
appointments.duplicated().sum()

np.int64(0)

In [ ]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status,AppointmentDateTime
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled,2023-06-28 08:00:00
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled,2023-09-01 09:15:00
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show,2023-07-06 12:45:00

In [ ]:
appointments.drop(columns=['appointment_date','appointment_time'])

,appointment_id,patient_id,doctor_id,reason_for_visit,status,AppointmentDateTime
0,A001,P034,D009,Therapy,Scheduled,2023-08-09 15:15:00
1,A002,P032,D004,Therapy,No-show,2023-06-09 14:30:00
2,A003,P048,D004,Consultation,Cancelled,2023-06-28 08:00:00
3,A004,P025,D006,Consultation,Cancelled,2023-09-01 09:15:00
4,A005,P040,D003,Emergency,No-show,2023-07-06 12:45:00
...,...,...,...,...,...,...
195,A196,P045,D006,Checkup,Cancelled,2023-10-26 09:45:00
196,A197,P001,D005,Emergency,No-show,2023-04-01 13:30:00
197,A198,P022,D006,Therapy,No-show,2023-05-15 08:30:00
198,A199,P017,D001,Follow-up,Completed,2023-05-01 12:45:00
199,A200,P007,D005,Consultation,Cancelled,2023-12-30 10:15:00

In [ ]:
appointments['Hour'] = appointments['AppointmentDateTime'].dt.hour
appointments['Day'] = appointments['AppointmentDateTime'].dt.day_name()
appointments['Month'] = appointments['AppointmentDateTime'].dt.month
appointments['Weekday'] = appointments['AppointmentDateTime'].dt.weekday

In [ ]:
appointments.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status,AppointmentDateTime,Hour,Day,Month,Weekday
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,8,2
1,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00,14,Friday,6,4
2,A003,P048,D004,2023-06-28,8:00:00,Consultation,Cancelled,2023-06-28 08:00:00,8,Wednesday,6,2
3,A004,P025,D006,2023-09-01,9:15:00,Consultation,Cancelled,2023-09-01 09:15:00,9,Friday,9,4
4,A005,P040,D003,2023-07-06,12:45:00,Emergency,No-show,2023-07-06 12:45:00,12,Thursday,7,3

In [ ]:
billing.head()

,bill_id,patient_id,treatment_id,bill_date,amount,payment_method,payment_status
0,B001,P034,T001,2023-08-09,3941.97,Insurance,Pending
1,B002,P032,T002,2023-06-09,4158.44,Insurance,Paid
2,B003,P048,T003,2023-06-28,3731.55,Insurance,Paid
3,B004,P025,T004,2023-09-01,4799.86,Insurance,Failed
4,B005,P040,T005,2023-07-06,582.05,Credit Card,Pending

In [ ]:
billing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bill_id         200 non-null    object
 1   patient_id      200 non-null    object
 2   treatment_id    200 non-null    object
 3   bill_date       200 non-null    object
 4   amount          200 non-null    float64
 5   payment_method  200 non-null    object
 6   payment_status  200 non-null    object
dtypes: float64(1), object(6)
memory usage: 11.1+ KB

In [ ]:
billing['bill_date'] = pd.to_datetime(billing['bill_date'])

In [ ]:
doctors.head()

,doctor_id,first_name,last_name,specialization,phone_number,years_experience,hospital_branch,email
0,D001,David,Taylor,Dermatology,8322010158,17,Westside Clinic,dr.david.taylor@hospital.com
1,D002,Jane,Davis,Pediatrics,9004382050,24,Eastside Clinic,dr.jane.davis@hospital.com
2,D003,Jane,Smith,Pediatrics,8737740598,19,Eastside Clinic,dr.jane.smith@hospital.com
3,D004,David,Jones,Pediatrics,6594221991,28,Central Hospital,dr.david.jones@hospital.com
4,D005,Sarah,Taylor,Dermatology,9118538547,26,Central Hospital,dr.sarah.taylor@hospital.com

In [ ]:
doctors.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   doctor_id         10 non-null     object
 1   first_name        10 non-null     object
 2   last_name         10 non-null     object
 3   specialization    10 non-null     object
 4   phone_number      10 non-null     int64
 5   years_experience  10 non-null     int64
 6   hospital_branch   10 non-null     object
 7   email             10 non-null     object
dtypes: int64(2), object(6)
memory usage: 772.0+ bytes

In [ ]:
treatments.head()

,treatment_id,appointment_id,treatment_type,description,cost,treatment_date
0,T001,A001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,T002,A002,MRI,Advanced protocol,4158.44,2023-06-09
2,T003,A003,MRI,Standard procedure,3731.55,2023-06-28
3,T004,A004,MRI,Basic screening,4799.86,2023-09-01
4,T005,A005,ECG,Standard procedure,582.05,2023-07-06

In [ ]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   treatment_id    200 non-null    object
 1   appointment_id  200 non-null    object
 2   treatment_type  200 non-null    object
 3   description     200 non-null    object
 4   cost            200 non-null    float64
 5   treatment_date  200 non-null    object
dtypes: float64(1), object(5)
memory usage: 9.5+ KB

In [ ]:
treatments['treatment_date'] = pd.to_datetime(treatments['treatment_date'])

In [ ]:
df = appointments.merge(patients,on='patient_id',how='left')

In [ ]:
df = df.merge(doctors, on='doctor_id',how='left')

In [ ]:
df = df.merge(billing,on='patient_id',how='left')

In [ ]:
df = df.merge(treatment,on='appointment_id',how = 'left')

In [ ]:
df.head()

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status,AppointmentDateTime,Hour,Day,...,treatment_id_x,bill_date,amount,payment_method,payment_status,treatment_id_y,treatment_type,description,cost,treatment_date
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,T001,2023-08-09,3941.97,Insurance,Pending,T001,Chemotherapy,Basic screening,3941.97,2023-08-09
1,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,T043,2023-03-29,3207.25,Insurance,Failed,T001,Chemotherapy,Basic screening,3941.97,2023-08-09
2,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,T093,2023-04-09,1955.17,Credit Card,Failed,T001,Chemotherapy,Basic screening,3941.97,2023-08-09
3,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00,14,Friday,...,T002,2023-06-09,4158.44,Insurance,Paid,T002,MRI,Advanced protocol,4158.44,2023-06-09
4,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00,14,Friday,...,T047,2023-05-02,1454.20,Insurance,Failed,T002,MRI,Advanced protocol,4158.44,2023-06-09

In [ ]:
treatment_agg = treatments.groupby('appointment_id').agg({
    'cost': 'sum',
    'treatment_type': 'count'
}).reset_index()

treatment_agg.rename(columns={
    'cost': 'TotalTreatmentCost',
    'treatment_type': 'NumTreatments'
}, inplace=True)

df = df.merge(treatment_agg, on='appointment_id', how='left')

In [ ]:
df

,appointment_id,patient_id,doctor_id,appointment_date,appointment_time,reason_for_visit,status,AppointmentDateTime,Hour,Day,...,amount,payment_method,payment_status,treatment_id_y,treatment_type,description,cost,treatment_date,TotalTreatmentCost,NumTreatments
0,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,3941.97,Insurance,Pending,T001,Chemotherapy,Basic screening,3941.97,2023-08-09,3941.97,1
1,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,3207.25,Insurance,Failed,T001,Chemotherapy,Basic screening,3941.97,2023-08-09,3941.97,1
2,A001,P034,D009,2023-08-09,15:15:00,Therapy,Scheduled,2023-08-09 15:15:00,15,Wednesday,...,1955.17,Credit Card,Failed,T001,Chemotherapy,Basic screening,3941.97,2023-08-09,3941.97,1
3,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00,14,Friday,...,4158.44,Insurance,Paid,T002,MRI,Advanced protocol,4158.44,2023-06-09,4158.44,1
4,A002,P032,D004,2023-06-09,14:30:00,Therapy,No-show,2023-06-09 14:30:00,14,Friday,...,1454.20,Insurance,Failed,T002,MRI,Advanced protocol,4158.44,2023-06-09,4158.44,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
997,A199,P017,D001,2023-05-01,12:45:00,Follow-up,Completed,2023-05-01 12:45:00,12,Monday,...,1472.17,Credit Card,Paid,T199,Chemotherapy,Basic screening,1472.17,2023-05-01,1472.17,1
998,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled,2023-12-30 10:15:00,10,Saturday,...,2097.48,Cash,Failed,T200,X-Ray,Basic screening,3288.15,2023-12-30,3288.15,1
999,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled,2023-12-30 10:15:00,10,Saturday,...,2120.61,Insurance,Paid,T200,X-Ray,Basic screening,3288.15,2023-12-30,3288.15,1
1000,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled,2023-12-30 10:15:00,10,Saturday,...,3228.14,Credit Card,Paid,T200,X-Ray,Basic screening,3288.15,2023-12-30,3288.15,1
1001,A200,P007,D005,2023-12-30,10:15:00,Consultation,Cancelled,2023-12-30 10:15:00,10,Saturday,...,3288.15,Insurance,Paid,T200,X-Ray,Basic screening,3288.15,2023-12-30,3288.15,1

In [ ]:
print(df.shape)
print(df.head())

# Check duplicates after merge
print(df.duplicated(subset=['appointment_id']).sum())

(1002, 42)
  appointment_id patient_id doctor_id appointment_date appointment_time  \
0           A001       P034      D009       2023-08-09         15:15:00
1           A001       P034      D009       2023-08-09         15:15:00
2           A001       P034      D009       2023-08-09         15:15:00
3           A002       P032      D004       2023-06-09         14:30:00
4           A002       P032      D004       2023-06-09         14:30:00

  reason_for_visit     status AppointmentDateTime  Hour        Day  ...  \
0          Therapy  Scheduled 2023-08-09 15:15:00    15  Wednesday  ...
1          Therapy  Scheduled 2023-08-09 15:15:00    15  Wednesday  ...
2          Therapy  Scheduled 2023-08-09 15:15:00    15  Wednesday  ...
3          Therapy    No-show 2023-06-09 14:30:00    14     Friday  ...
4          Therapy    No-show 2023-06-09 14:30:00    14     Friday  ...

    amount  payment_method payment_status treatment_id_y treatment_type  \
0  3941.97       Insurance        Pending           T001   Chemotherapy
1  3207.25       Insurance         Failed           T001   Chemotherapy
2  1955.17     Credit Card         Failed           T001   Chemotherapy
3  4158.44       Insurance           Paid           T002            MRI
4  1454.20       Insurance         Failed           T002            MRI

         description     cost treatment_date TotalTreatmentCost NumTreatments
0    Basic screening  3941.97     2023-08-09            3941.97             1
1    Basic screening  3941.97     2023-08-09            3941.97             1
2    Basic screening  3941.97     2023-08-09            3941.97             1
3  Advanced protocol  4158.44     2023-06-09            4158.44             1
4  Advanced protocol  4158.44     2023-06-09            4158.44             1

[5 rows x 42 columns]
802

In [ ]:
df.columns

Index(['appointment_id', 'patient_id', 'doctor_id', 'appointment_date',
       'appointment_time', 'reason_for_visit', 'status', 'AppointmentDateTime',
       'Hour', 'Day', 'Month', 'Weekday', 'first_name_x', 'last_name_x',
       'gender', 'date_of_birth', 'contact_number', 'address',
       'registration_date', 'insurance_provider', 'insurance_number',
       'email_x', 'first_name_y', 'last_name_y', 'specialization',
       'phone_number', 'years_experience', 'hospital_branch', 'email_y',
       'bill_id', 'treatment_id_x', 'bill_date', 'amount', 'payment_method',
       'payment_status', 'treatment_id_y', 'treatment_type', 'description',
       'cost', 'treatment_date', 'TotalTreatmentCost', 'NumTreatments'],
      dtype='object')

In [ ]:
df.rename(columns={
    'first_name_x': 'PatientFirstName',
    'last_name_x': 'PatientLastName',
    'first_name_y': 'DoctorFirstName',
    'last_name_y': 'DoctorLastName',
    'email_x': 'PatientEmail',
    'email_y': 'DoctorEmail'
}, inplace=True)

In [ ]:
df.drop(columns=[
    'treatment_id_x',
    'treatment_id_y'
], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1002 entries, 0 to 1001
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   appointment_id       1002 non-null   object
 1   patient_id           1002 non-null   object
 2   doctor_id            1002 non-null   object
 3   appointment_date     1002 non-null   object
 4   appointment_time     1002 non-null   object
 5   reason_for_visit     1002 non-null   object
 6   status               1002 non-null   object
 7   AppointmentDateTime  1002 non-null   datetime64[ns]
 8   Hour                 1002 non-null   int32
 9   Day                  1002 non-null   object
 10  Month                1002 non-null   int32
 11  Weekday              1002 non-null   int32
 12  PatientFirstName     1002 non-null   object
 13  PatientLastName      1002 non-null   object
 14  gender               1002 non-null   object
 15  date_of_birth        1002 non-null   datetime64[ns]
 16  contact_number       1002 non-null   int64
 17  address              1002 non-null   object
 18  registration_date    1002 non-null   datetime64[ns]
 19  insurance_provider   1002 non-null   object
 20  insurance_number     1002 non-null   object
 21  PatientEmail         1002 non-null   object
 22  DoctorFirstName      1002 non-null   object
 23  DoctorLastName       1002 non-null   object
 24  specialization       1002 non-null   object
 25  phone_number         1002 non-null   int64
 26  years_experience     1002 non-null   int64
 27  hospital_branch      1002 non-null   object
 28  DoctorEmail          1002 non-null   object
 29  bill_id              1002 non-null   object
 30  bill_date            1002 non-null   datetime64[ns]
 31  amount               1002 non-null   float64
 32  payment_method       1002 non-null   object
 33  payment_status       1002 non-null   object
 34  treatment_type       1002 non-null   object
 35  description          1002 non-null   object
 36  cost                 1002 non-null   float64
 37  treatment_date       1002 non-null   object
 38  TotalTreatmentCost   1002 non-null   float64
 39  NumTreatments        1002 non-null   int64
dtypes: datetime64[ns](4), float64(3), int32(3), int64(4), object(26)
memory usage: 301.5+ KB

In [ ]:
df['Revenue'] = df['amount'].fillna(0)

In [ ]:
df['TimeSlot'] = pd.cut(
    df['Hour'],
    bins=[0, 6, 12, 18, 24],
    labels=['Night', 'Morning', 'Afternoon', 'Evening']
)

In [ ]:
df['DoctorName'] = df['DoctorFirstName'] + ' ' + df['DoctorLastName']

In [ ]:
# Check duplicates
print(df.duplicated(subset=['appointment_id']).sum())

# Check nulls
print(df.isnull().sum())

# Check revenue distribution
print(df['Revenue'].describe())

802
appointment_id         0
patient_id             0
doctor_id              0
appointment_date       0
appointment_time       0
reason_for_visit       0
status                 0
AppointmentDateTime    0
Hour                   0
Day                    0
Month                  0
Weekday                0
PatientFirstName       0
PatientLastName        0
gender                 0
date_of_birth          0
contact_number         0
address                0
registration_date      0
insurance_provider     0
insurance_number       0
PatientEmail           0
DoctorFirstName        0
DoctorLastName         0
specialization         0
phone_number           0
years_experience       0
hospital_branch        0
DoctorEmail            0
bill_id                0
bill_date              0
amount                 0
payment_method         0
payment_status         0
treatment_type         0
description            0
cost                   0
treatment_date         0
TotalTreatmentCost     0
NumTreatments          0
Revenue                0
TimeSlot               0
DoctorName             0
dtype: int64
count    1002.000000
mean     2742.804551
std      1280.623652
min       534.030000
25%      1555.890000
50%      2835.770000
75%      3815.930000
max      4973.630000
Name: Revenue, dtype: float64

In [ ]:
df['PatientCount'] = 1

In [ ]:
dept_summary = df.groupby('specialization').agg({
    'PatientCount': 'sum',
    'Revenue': 'sum'
}).reset_index()

In [ ]:
dept_summary

  specialization  PatientCount     Revenue
0    Dermatology           353   965566.84
1       Oncology           177   493428.71
2     Pediatrics           472  1289294.61

In [ ]:
doctor_summary = df.groupby('DoctorName').agg({
    'PatientCount': 'sum',
    'Revenue': 'sum'
}).reset_index()

In [ ]:
doctor_summary

     DoctorName  PatientCount    Revenue
0    Alex Davis           121  339280.84
1   David Jones            73  191212.99
2  David Taylor           129  336851.92
3    Jane Davis            88  264650.98
4    Jane Smith           106  279957.14
5   Linda Brown            82  234358.03
6  Linda Wilson           115  304846.08
7  Robert Davis            62  188582.63
8   Sarah Smith            84  214192.66
9  Sarah Taylor           142  394356.89

In [ ]:
time_summary = df.groupby('Hour')['PatientCount'].sum().reset_index()

In [ ]:
time_summary

   Hour  PatientCount
0     8           114
1     9            75
2    10            98
3    11            95
4    12            95
5    13           103
6    14           106
7    15           156
8    16            71
9    17            89

In [ ]:
day_summary = df.groupby('Day')['PatientCount'].sum().reset_index()

In [ ]:
day_summary

         Day  PatientCount
0     Friday           109
1     Monday           130
2   Saturday           104
3     Sunday           132
4   Thursday           146
5    Tuesday           198
6  Wednesday           183

In [ ]:
treatment_summary = df.groupby('treatment_type').agg({
    'PatientCount': 'sum',
    'Revenue': 'sum'
}).reset_index()

In [ ]:
df.to_csv("hospital_final.csv", index=False)

dept_summary.to_csv("dept_summary.csv", index=False)
doctor_summary.to_csv("doctor_summary.csv", index=False)
time_summary.to_csv("time_summary.csv", index=False)
day_summary.to_csv("day_summary.csv", index=False)
treatment_summary.to_csv("treatment_summary.csv", index=False)

In [ ]:
import os

print(os.getcwd())
print(os.listdir())

/content
['.config', 'doctor_summary.csv', 'appointments.csv', 'treatment_summary.csv', 'day_summary.csv', 'patients.csv', 'doctors.csv', 'time_summary.csv', 'hospital_final.csv', 'dept_summary.csv', 'treatments.csv', 'billing.csv', 'sample_data']

In [ ]:
from google.colab import files
files.download('hospital_final.csv')

In [ ]:
files.download('dept_summary.csv')
files.download('doctor_summary.csv')
files.download('time_summary.csv')
files.download('day_summary.csv')
files.download('treatment_summary.csv')